# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20170313_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blogs', models.ManyToManyField(related_name='categories', to='blogs.Blog')),
            ],
        ),
    ]
