# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20170426_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likepost',
            options={'verbose_name': '\u041b\u0430\u0439\u043a \u043f\u043e\u0441\u0442\u0430', 'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438\u0438 \u043f\u043e\u0441\u0442\u043e\u0432'},
        ),
    ]
